language: python # => 1
python: # => 2
   - "3.7"
   - "3.8"

env: # => 4
   -DJANGO=2.2
install: # => 5
   - pip install -q Django==$DJANGO
   - pip install -r requirements.txt
before_script: # => 6
    
script: # => 7
   - black --check .
   - flake8 .
   - coverage run --source=polls manage.py test polls
   
after-success:
   - coveralls

before_deploy: "echo 'ready?'"
deploy:
  on:
    branch: main
  provider: elasticbeanstalk
  access_key_id: $SecretKeyId
  secret_access_key: $SecretKey
  region: "us-west-2"
  app: "app-mysite"
  env: "env-mysite"
  bucket_name: "elasticbeanstalk-us-west-2-124178988437"

after_deploy: "echo 'Done'"