language: python # => 1
    python: # => 2
      - "3.7"
      - "3.8"

    env: # => 4
      -DJANGO=2.2
    install: # => 5
      - pip install -q Django==$DJANGO
      - pip install -r requirements.txt
    before_script: # => 6
    
    script: # => 7
      - python manage.py test
